name: bagahon
description: A Nike-style e-commerce Flutter app


environment: 
  sdk: '>=3.0.0 <4.0.0' 
  flutter: ">=3.10.0"   

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.1
  path: ^1.8.3
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.6